[package]
name = "cloudflare-ddns"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
cloudflare = "0.11.0"
public-ip = "0.2.2"
tokio = { version = "1.34.0", features = ["full"] }

[release]
lto = true
